name: postman_regression_test_execution_and_reports

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman Tests
        run: newman run api_testing/Regression_Suite_API/Regression_Suite_API.postman_collection.json --environment=DEV_Environment/DEV_Env.postman_environment.json --reporters cli,htmlextra

      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports-regression-test-execution
          path: newman
